database:
  host: host.docker.internal
  port: 5432
  user: postgres
  password: postgres
  name: postgres # 数据库名称

proxy_node:
  ip: oneshare.com.cn
  ssh_port: 22
  username: ubuntu
  password: alano+1234567