tls:
  options:
    anylinker_tls:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/anylinker.pem
        keyFile: /etc/traefik/certs/anylinker_key.key
  certificates:
    - certFile: /etc/traefik/certs/anylinker.pem
      keyFile: /etc/traefik/certs/anylinker_key.key